import type { Patient, ClinicalNote, PatientDocument, Appointment } from '../types';

export const initialSeedPatients: Patient[] = [
  {
    id: 'pat-1',
    firstName: 'Sophia',
    lastName: 'Rodriguez',
    dateOfBirth: '1988-06-14',
    gender: 'Female',
    phone: '(555) 234-5678',
    email: 'sophia.rodriguez@example.com',
    address: '742 Evergreen Terrace, Springfield, IL',
    emergencyContact: {
      name: 'Carlos Rodriguez',
      relationship: 'Spouse',
      phone: '(555) 987-6543',
    },
    insurance: {
      provider: 'Delta Dental Premier',
      policyNumber: 'DEL-992014',
      groupNumber: 'GRP-5541',
    },
    riskStatus: 'CRITICAL',
    medicalHistory: {
      bleedingDisorder: true,
      diabetes: false,
      hypertension: true,
      penicillinAllergy: true,
      latexAllergy: true,
      pregnant: false,
      infectiousDisease: false,
      heartCondition: false,
      otherAlerts: 'History of post-extraction hemorrhage. Requires non-latex gloves and antibiotic alternative.',
    },
    teethConditions: [
      { toothNumber: 3, condition: 'CROWN', notes: 'Porcelain fused to metal crown placed in 2022', updatedAt: '2022-04-12' },
      { toothNumber: 14, condition: 'ROOT_CANAL', notes: 'Obturated root canals with gutta-percha', updatedAt: '2023-01-15' },
      { toothNumber: 19, condition: 'CARIES', notes: 'Occlusal cavity requiring Class I composite filling', updatedAt: '2025-02-10' },
      { toothNumber: 30, condition: 'MISSING', notes: 'Extracted in 2018 due to severe decay', updatedAt: '2018-09-02' },
    ],
    lastVisitDate: '2025-03-01',
    createdDate: '2024-01-15',
  },
  {
    id: 'pat-2',
    firstName: 'Marcus',
    lastName: 'Chen',
    dateOfBirth: '1992-11-03',
    gender: 'Male',
    phone: '(555) 345-6789',
    email: 'marcus.chen@example.com',
    address: '1204 Pine Street, Apt 4B, Chicago, IL',
    emergencyContact: {
      name: 'Mei Chen',
      relationship: 'Sister',
      phone: '(555) 876-5432',
    },
    insurance: {
      provider: 'MetLife Dental PPO',
      policyNumber: 'MET-88301',
      groupNumber: 'GRP-1200',
    },
    riskStatus: 'LOW',
    medicalHistory: {
      bleedingDisorder: false,
      diabetes: false,
      hypertension: false,
      penicillinAllergy: false,
      latexAllergy: false,
      pregnant: false,
      infectiousDisease: false,
      heartCondition: false,
    },
    teethConditions: [
      { toothNumber: 1, condition: 'MISSING', notes: 'Third molar extracted', updatedAt: '2020-05-10' },
      { toothNumber: 16, condition: 'MISSING', notes: 'Third molar extracted', updatedAt: '2020-05-10' },
      { toothNumber: 17, condition: 'MISSING', notes: 'Third molar extracted', updatedAt: '2020-05-10' },
      { toothNumber: 32, condition: 'MISSING', notes: 'Third molar extracted', updatedAt: '2020-05-10' },
      { toothNumber: 8, condition: 'FILLING', notes: 'Mesial composite filling', updatedAt: '2024-06-20' },
    ],
    lastVisitDate: '2025-02-18',
    createdDate: '2023-08-10',
  },
  {
    id: 'pat-3',
    firstName: 'Eleanor',
    lastName: 'Vance',
    dateOfBirth: '1965-04-22',
    gender: 'Female',
    phone: '(555) 456-7890',
    email: 'eleanor.vance@example.com',
    address: '88 Hill House Lane, Evanston, IL',
    emergencyContact: {
      name: 'Luke Sanderson',
      relationship: 'Nephew',
      phone: '(555) 765-4321',
    },
    insurance: {
      provider: 'Cigna Dental Health',
      policyNumber: 'CG-400192',
    },
    riskStatus: 'HIGH',
    medicalHistory: {
      bleedingDisorder: false,
      diabetes: true,
      hypertension: true,
      penicillinAllergy: true,
      latexAllergy: false,
      pregnant: false,
      infectiousDisease: false,
      heartCondition: true,
      otherAlerts: 'Pre-medication protocol required before surgical procedures.',
    },
    teethConditions: [
      { toothNumber: 12, condition: 'EXTRACTION_NEEDED', notes: 'Severe periodontal bone loss, non-restorable', updatedAt: '2025-02-28' },
      { toothNumber: 13, condition: 'BRIDGE', notes: 'Abutment for 3-unit pontic bridge', updatedAt: '2021-11-14' },
      { toothNumber: 15, condition: 'BRIDGE', notes: 'Abutment for 3-unit pontic bridge', updatedAt: '2021-11-14' },
      { toothNumber: 31, condition: 'IMPLANT', notes: 'Titanium fixture integrated with crown', updatedAt: '2023-09-18' },
    ],
    lastVisitDate: '2025-02-28',
    createdDate: '2022-03-05',
  },
];

export const initialSeedNotes: ClinicalNote[] = [
  {
    id: 'note-1',
    patientId: 'pat-1',
    date: '2025-03-01',
    dentistName: 'Dr. Sarah Jenkins, DDS',
    chiefComplaint: 'Patient presents with sharp sensitivity on lower left molars when drinking cold liquids.',
    clinicalFindings: 'Visual inspection reveals marginal discoloration and secondary caries on tooth #19 occlusal surface. Cold test positive on #19 with lingering pain.',
    diagnosis: 'Reversible pulpitis on #19 secondary to occlusal caries.',
    treatmentRendered: 'Local anesthesia administered (2% Lidocaine with 1:100k Epi, latex-free gloves used). Excavated caries on #19, placed composite restoration.',
    toothNumbers: [19],
    procedureCode: 'D2391',
  },
  {
    id: 'note-2',
    patientId: 'pat-2',
    date: '2025-02-18',
    dentistName: 'Dr. Michael Chang, DMD',
    chiefComplaint: 'Routine 6-month prophylaxis and oral examination.',
    clinicalFindings: 'Periodontal probing depths within 2-3mm throughout. Mild supragingival plaque accumulation on mandibular anterior linguals.',
    diagnosis: 'Healthy periodontal tissues with mild gingivitis.',
    treatmentRendered: 'Full mouth scaling and polishing performed. Topical fluoride treatment applied.',
    procedureCode: 'D1110',
  },
];

export const initialSeedDocuments: PatientDocument[] = [
  {
    id: 'doc-1',
    patientId: 'pat-1',
    title: 'Bitewing X-Ray - Lower Left Quadrant',
    tag: 'X-Ray',
    fileName: 'xray_pat1_quad3.png',
    fileType: 'image/png',
    uploadDate: '2025-03-01',
    fileSize: 245000,
    dataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400"><rect width="100%" height="100%" fill="%230f172a"/><text x="50%" y="40%" font-family="sans-serif" font-size="20" fill="%2338bdf8" text-anchor="middle" font-weight="bold">DIGITAL DENTAL RADIOGRAPH (X-RAY)</text><text x="50%" y="55%" font-family="sans-serif" font-size="14" fill="%2394a3b8" text-anchor="middle">Patient: Sophia Rodriguez | Quad 3 Bitewing</text><path d="M 200 250 Q 300 150 400 250" stroke="%23f87171" stroke-width="4" fill="none"/><circle cx="300" cy="200" r="25" fill="%23ef4444" opacity="0.6"/><text x="300" y="205" font-family="sans-serif" font-size="12" fill="white" text-anchor="middle">CARIES #19</text></svg>',
  },
  {
    id: 'doc-2',
    patientId: 'pat-1',
    title: 'Informed Consent Form - Surgical Extraction & Anesthesia',
    tag: 'Consent Form',
    fileName: 'consent_rodriguez_signed.pdf',
    fileType: 'application/pdf',
    uploadDate: '2024-01-15',
    fileSize: 180000,
    dataUrl: 'data:application/pdf;base64,JVBERi0xLjQKJ...',
  },
  {
    id: 'doc-3',
    patientId: 'pat-3',
    title: 'Panoramic Radiograph (OPG)',
    tag: 'X-Ray',
    fileName: 'opg_vance_2025.png',
    fileType: 'image/png',
    uploadDate: '2025-02-28',
    fileSize: 512000,
    dataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400"><rect width="100%" height="100%" fill="%23020617"/><text x="50%" y="30%" font-family="sans-serif" font-size="22" fill="%23818cf8" text-anchor="middle" font-weight="bold">PANORAMIC RADIOGRAPH (OPG)</text><text x="50%" y="45%" font-family="sans-serif" font-size="14" fill="%2394a3b8" text-anchor="middle">Patient: Eleanor Vance | Date: 2025-02-28</text><rect x="150" y="220" width="300" height="80" rx="15" fill="none" stroke="%2338bdf8" stroke-width="3"/><text x="300" y="265" font-family="sans-serif" font-size="14" fill="%23f43f5e" text-anchor="middle">Severe Bone Loss Tooth #12</text></svg>',
  },
];

export const initialSeedAppointments: Appointment[] = [
  {
    id: 'apt-1',
    patientId: 'pat-1',
    patientName: 'Sophia Rodriguez',
    date: '2025-03-15',
    time: '09:00',
    durationMinutes: 45,
    dentistName: 'Dr. Sarah Jenkins, DDS',
    treatmentType: 'Crown Preparation & Impression',
    status: 'Scheduled',
    notes: 'Confirm latex-free operatory preparation prior to arrival.',
  },
  {
    id: 'apt-2',
    patientId: 'pat-2',
    patientName: 'Marcus Chen',
    date: '2025-03-15',
    time: '10:30',
    durationMinutes: 30,
    dentistName: 'Dr. Michael Chang, DMD',
    treatmentType: 'Composite Filling #19',
    status: 'Scheduled',
  },
  {
    id: 'apt-3',
    patientId: 'pat-3',
    patientName: 'Eleanor Vance',
    date: '2025-03-16',
    time: '14:00',
    durationMinutes: 60,
    dentistName: 'Dr. Sarah Jenkins, DDS',
    treatmentType: 'Surgical Extraction #12',
    status: 'Scheduled',
    notes: 'Check pre-medication protocol prior to surgical start.',
  },
];
